(()=>{"use strict";
const URL="https://sybxbyaywznbwipbssso.supabase.co/functions/v1/admin-orders";
const $=s=>document.querySelector(s); let pin=sessionStorage.getItem("esh-admin-pin")||"";
const money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0);
const esc=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const toast=m=>{const t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)};
const settings=()=>({name:localStorage.getItem("esh-sender-name")||"Eletroshopp",cep:localStorage.getItem("esh-sender-cep")||"84261-000",address:localStorage.getItem("esh-sender-address")||"",city:localStorage.getItem("esh-sender-city")||""});
function fillSettings(){const s=settings();$("#senderName").value=s.name;$("#senderCep").value=s.cep;$("#senderAddress").value=s.address;$("#senderCity").value=s.city}
async function api(method="GET",body){const r=await fetch(URL,{method,headers:{"Content-Type":"application/json","x-admin-pin":pin},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Acesso negado");return d}
function items(o){let a=Array.isArray(o.items)?o.items:[];return a.length?a.map(x=>'<div class="item"><span>'+esc((x.quantity||1)+"× "+(x.name||"Produto"))+'</span><b>'+money((Number(x.price)||0)*(Number(x.quantity)||1))+'</b></div>').join(""):'<div class="empty">Itens não registrados.</div>'}
function printDoc(o,label=false){const s=settings(),b=o.buyer||{},f=o.freight||{},its=Array.isArray(o.items)?o.items:[],date=o.created_at?new Date(o.created_at).toLocaleString("pt-BR"):"";
const body=label?'<div class="label"><h1>ELETROSHOPP</h1><h2>ETIQUETA DE ENVIO</h2><div class="big">'+esc(o.id)+'</div><hr><b>REMETENTE</b><p>'+esc(s.name)+'<br>'+esc(s.address||"Endereço não configurado")+'<br>'+esc(s.city)+'<br>CEP: '+esc(s.cep)+'</p><b>DESTINATÁRIO</b><p>'+esc(b.name)+'<br>'+esc(b.address)+'<br>CEP: '+esc(b.cep)+'<br>Tel.: '+esc(b.phone)+'</p><hr><b>CONTEÚDO / VALORES</b>'+its.map(x=>'<p>'+esc((x.quantity||1)+"× "+x.name)+' — '+money((x.price||0)*(x.quantity||1))+'</p>').join("")+'<p>Frete: '+money(f.price||0)+'<br><strong>Total: '+money(o.grand_total||0)+'</strong></p><div class="barcode">'+esc(o.id)+'</div></div>':
'<div class="sheet"><h1>ELETROSHOPP — PEDIDO</h1><p><b>Pedido:</b> '+esc(o.id)+'<br><b>Data:</b> '+esc(date)+'<br><b>Status:</b> '+esc(o.status)+'</p><h2>Cliente</h2><p>'+esc(b.name)+'<br>WhatsApp: '+esc(b.phone)+'<br>CEP: '+esc(b.cep)+'<br>'+esc(b.address)+'</p><h2>Produtos</h2>'+its.map(x=>'<p>'+esc((x.quantity||1)+"× "+x.name)+' — unitário '+money(x.price||0)+' — subtotal '+money((x.price||0)*(x.quantity||1))+'</p>').join("")+'<hr><p>Subtotal: '+money(o.total_products||0)+'<br>Frete: '+money(f.price||0)+' ('+esc(f.name||"")+' / '+esc(f.days||"")+' dias)<br><strong>Total: '+money(o.grand_total||0)+'</strong></p><p>Pagamento: '+esc(o.payment||"A combinar")+'</p></div>';
const w=window.open("","_blank");w.document.write('<!doctype html><html><head><title>'+esc(o.id)+'</title><style>body{font:14px Arial;color:#111;margin:0}.sheet{width:800px;margin:30px auto}.label{width:100mm;min-height:150mm;padding:7mm;box-sizing:border-box}.label h1{text-align:center;margin:0}.label h2{text-align:center;font-size:16px}.big{font-size:22px;font-weight:700;text-align:center}.barcode{margin-top:18px;border:2px dashed #111;padding:10px;text-align:center;font:700 18px monospace;letter-spacing:3px}@page{size:auto;margin:10mm}@media print{.sheet{margin:0;width:auto}}</style></head><body>'+body+'</body></html>');w.document.close();w.focus();setTimeout(()=>w.print(),300)}
function render(list){$("#summary").textContent=list.length+" pedido(s)";$("#orders").innerHTML=list.length?list.map(o=>{const b=o.buyer||{},f=o.freight||{};return '<article class="order"><div class="order-head"><div><div class="order-id">'+esc(o.id)+'</div><small>'+esc(o.created_at?new Date(o.created_at).toLocaleString("pt-BR"):"")+'</small></div><span class="badge">'+esc(o.status||"novo")+'</span></div><div class="meta"><div><small>Cliente</small>'+esc(b.name||"—")+'</div><div><small>WhatsApp</small>'+esc(b.phone||"—")+'</div><div><small>Entrega</small>'+esc(b.cep||"—")+'</div></div><div><small>Endereço</small><p>'+esc(b.address||"—")+'</p></div><div class="items">'+items(o)+'</div><div class="totals"><span>Produtos: <b>'+money(o.total_products)+'</b></span><span>Frete: <b>'+money(f.price||0)+'</b></span><strong>Total: '+money(o.grand_total)+'</strong></div><div class="order-actions"><select data-status="'+esc(o.id)+'"><option '+(o.status==="novo"?"selected":"")+' value="novo">Novo</option><option '+(o.status==="em_separacao"?"selected":"")+' value="em_separacao">Em separação</option><option '+(o.status==="enviado"?"selected":"")+' value="enviado">Enviado</option><option '+(o.status==="entregue"?"selected":"")+' value="entregue">Entregue</option><option '+(o.status==="cancelado"?"selected":"")+' value="cancelado">Cancelado</option></select><button data-print="'+esc(o.id)+'">🖨 Imprimir pedido</button><button data-label="'+esc(o.id)+'">🏷 Imprimir etiqueta</button></div></article>'}).join(""):'<div class="panel empty">Nenhum pedido encontrado.</div>'}
let orders=[];
async function load(){try{orders=await api();render(Array.isArray(orders)?orders:[])}catch(e){toast(e.message);if(e.message==="Acesso negado")logout()}}
function logout(){sessionStorage.removeItem("esh-admin-pin");pin="";$("#app").hidden=true;$("#login").hidden=false}
$("#enter").onclick=async()=>{pin=$("#pin").value.trim();if(!pin)return;try{const d=await api();sessionStorage.setItem("esh-admin-pin",pin);$("#login").hidden=true;$("#app").hidden=false;fillSettings();render(Array.isArray(d)?d:[]);orders=d}catch(e){$("#loginMsg").textContent="PIN inválido ou painel indisponível."}};
$("#pin").addEventListener("keydown",e=>{if(e.key==="Enter")$("#enter").click()});
$("#refresh").onclick=load;$("#settingsBtn").onclick=()=>{$("#settings").hidden=!$("#settings").hidden};
$("#saveSettings").onclick=()=>{localStorage.setItem("esh-sender-name",$("#senderName").value);localStorage.setItem("esh-sender-cep",$("#senderCep").value);localStorage.setItem("esh-sender-address",$("#senderAddress").value);localStorage.setItem("esh-sender-city",$("#senderCity").value);toast("Remetente salvo")};
document.addEventListener("change",async e=>{const id=e.target.dataset.status;if(!id)return;try{await api("POST",{id,status:e.target.value});toast("Status atualizado");await load()}catch(x){toast(x.message)}});
document.addEventListener("click",e=>{const p=e.target.dataset.print,l=e.target.dataset.label;if(p){const o=orders.find(x=>x.id===p);if(o)printDoc(o,false)}if(l){const o=orders.find(x=>x.id===l);if(o)printDoc(o,true)}});
if(pin){$("#login").hidden=true;$("#app").hidden=false;fillSettings();load()}
})();