(()=>{"use strict";
const API="https://sybxbyaywznbwipbssso.supabase.co/functions/v1/admin-orders";
const $=s=>document.querySelector(s);
let pin="";
const money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0);
const esc=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
async function api(method="GET",body){const r=await fetch(API+"?t="+Date.now(),{method,cache:"no-store",headers:{"Content-Type":"application/json","x-admin-pin":pin},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Painel indisponível");return d}
function render(list){list=Array.isArray(list)?list:[];$("#summary").textContent=list.length+" pedido(s)";$("#orders").innerHTML=list.length?list.map(o=>{const b=o.buyer||{},f=o.freight||{},its=Array.isArray(o.items)?o.items:[];return '<article class="order"><div class="order-head"><div><b>'+esc(o.id)+'</b><small>'+esc(o.created_at?new Date(o.created_at).toLocaleString("pt-BR"):"")+'</small></div><span class="badge">'+esc(o.status||"novo")+'</span></div><div class="meta"><div><small>Cliente</small>'+esc(b.name||"—")+'</div><div><small>WhatsApp</small>'+esc(b.phone||"—")+'</div><div><small>CEP</small>'+esc(b.cep||"—")+'</div></div><p><small>Endereço</small>'+esc(b.address||"—")+'</p>'+its.map(x=>'<div class="item"><span>'+esc((x.quantity||1)+"× "+x.name)+'</span><b>'+money((x.price||0)*(x.quantity||1))+'</b></div>').join("")+'<div class="totals"><span>Produtos: <b>'+money(o.total_products)+'</b></span><span>Frete: <b>'+money(f.price)+'</b></span><strong>Total: '+money(o.grand_total)+'</strong></div><div class="order-actions"><select data-status="'+esc(o.id)+'"><option value="novo">Novo</option><option value="em_separacao">Em separação</option><option value="enviado">Enviado</option><option value="entregue">Entregue</option><option value="cancelado">Cancelado</option></select></div></article>'}).join(""):'<div class="panel empty">Nenhum pedido encontrado.</div>'}
async function load(){try{const d=await api();render(d);$("#loginMsg").textContent=""}catch(e){render([]);$("#summary").textContent="Não foi possível carregar os pedidos";$("#loginMsg").textContent="Painel aberto, mas não foi possível consultar os pedidos: "+e.message}}
function logout(){pin="";sessionStorage.removeItem("esh-admin-pin");$("#app").hidden=true;$("#login").hidden=false;$("#pin").value=""}
$("#enter").onclick=async()=>{pin=$("#pin").value.replace(/\D/g,"");$("#loginMsg").textContent="";if(pin!=="250808"){ $("#loginMsg").textContent="PIN inválido.";return }sessionStorage.setItem("esh-admin-pin",pin);$("#login").hidden=true;$("#app").hidden=false;$("#summary").textContent="Consultando pedidos...";await load()};
$("#pin").onkeydown=e=>{if(e.key==="Enter")$("#enter").click()};$("#refresh").onclick=load;$("#logout").onclick=logout;
document.addEventListener("change",async e=>{const id=e.target.dataset.status;if(!id)return;try{await api("POST",{id,status:e.target.value});await load()}catch(x){alert(x.message)}});
const saved=sessionStorage.getItem("esh-admin-pin");if(saved==="250808"){pin=saved;$("#login").hidden=true;$("#app").hidden=false;load()}
})();