(()=>{"use strict";
const API="https://sybxbyaywznbwipbssso.supabase.co/functions/v1/admin-orders";
const ADMIN_PIN="250808";let pin=sessionStorage.getItem("esh-admin-pin")||"",orders=[];
const $=s=>document.querySelector(s),money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0),esc=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const settings=()=>({name:localStorage.getItem("esh-sender-name")||"Eletroshopp",cep:localStorage.getItem("esh-sender-cep")||"84272-402",address:localStorage.getItem("esh-sender-address")||"",city:localStorage.getItem("esh-sender-city")||"Telêmaco Borba - PR"});
async function api(method="GET",body){const r=await fetch(API+"?t="+Date.now(),{method,cache:"no-store",headers:{"Content-Type":"application/json","x-admin-pin":pin,"Authorization":"Bearer "+pin,"Cache-Control":"no-cache"},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Painel indisponível");return d}
function printDoc(o,label=false){const s=settings(),b=o.buyer||{},f=o.freight||{},its=Array.isArray(o.items)?o.items:[];const origin=[s.address,s.city,"CEP: "+s.cep].filter(Boolean).map(esc).join("<br>");const destination=[b.address,"CEP: "+(b.cep||""),"WhatsApp: "+(b.phone||"")].filter(Boolean).map(esc).join("<br>");const products=its.map(x=>"<tr><td>"+esc((x.quantity||1)+"× "+(x.name||"Produto"))+"</td><td>"+money(x.price)+"</td><td>"+money((x.price||0)*(x.quantity||1))+"</td></tr>").join("");const freightName=esc(f.name||f.service||"Frete");const freightDays=esc(f.days||"");const html=label?'<div class="label"><h1>ELETROSHOPP</h1><h2>ETIQUETA DE ENVIO</h2><div class="code">'+esc(o.id)+'</div><hr><h3>LOCAL DE ENVIO — REMETENTE</h3><p><b>'+esc(s.name)+'</b><br>'+origin+'</p><h3>LOCAL DE ENTREGA — DESTINATÁRIO</h3><p><b>'+esc(b.name||"")+'</b><br>'+destination+'</p><h3>PRODUTOS</h3><table><thead><tr><th>Produto</th><th>Unit.</th><th>Subtotal</th></tr></thead><tbody>'+products+'</tbody></table><p><b>Subtotal produtos:</b> '+money(o.total_products)+'<br><b>Frete:</b> '+money(f.price)+' — '+freightName+(freightDays?" — "+freightDays+" dias":"")+'<br><strong>TOTAL:</strong> '+money(o.grand_total)+'</p><div class="barcode">|||| '+esc(o.id)+' ||||</div></div>':'<div class="sheet"><h1>ELETROSHOPP — PEDIDO</h1><p><b>Pedido:</b> '+esc(o.id)+'<br><b>Data:</b> '+esc(new Date(o.created_at).toLocaleString("pt-BR"))+'<br><b>Status:</b> '+esc(o.status)+'</p><h2>Envio</h2><p><b>Remetente:</b><br>'+esc(s.name)+'<br>'+origin+'</p><p><b>Destinatário:</b><br>'+esc(b.name||"")+'<br>'+destination+'</p><h2>Produtos</h2><table><thead><tr><th>Produto</th><th>Unit.</th><th>Subtotal</th></tr></thead><tbody>'+products+'</tbody></table><hr><p>Subtotal produtos: '+money(o.total_products)+'<br>Frete: '+money(f.price)+' — '+freightName+(freightDays?" — "+freightDays+" dias":"")+'<br><b>Total: '+money(o.grand_total)+'</b><br>Pagamento: '+esc(o.payment||"A combinar")+'</p></div>';const w=window.open("","_blank");if(!w){alert("Permita pop-ups para imprimir a etiqueta.");return}w.document.write('<!doctype html><html><head><title>'+esc(o.id)+'</title><style>body{font:14px Arial;color:#111;margin:20px}.sheet{max-width:850px;margin:auto}.label{width:100mm;min-height:150mm;padding:6mm;box-sizing:border-box}.label h1,.label h2{text-align:center}.code{text-align:center;font-size:20px;font-weight:bold}table{width:100%;border-collapse:collapse}th,td{padding:6px 3px;border-bottom:1px solid #ccc;text-align:left}.barcode{text-align:center;border:2px dashed #111;padding:12px;margin-top:18px;font:700 18px monospace;letter-spacing:2px}@page{margin:8mm}@media print{body{margin:0}}</style></head><body>'+html+'</body></html>');w.document.close();setTimeout(()=>w.print(),400)}
function render(list){list=Array.isArray(list)?list:[];$("#summary").textContent=list.length+" pedido(s)";$("#orders").innerHTML=list.length?list.map(o=>{const b=o.buyer||{},f=o.freight||{},its=Array.isArray(o.items)?o.items:[];return '<article class="order"><div class="order-head"><div><b>'+esc(o.id)+'</b><small>'+esc(o.created_at?new Date(o.created_at).toLocaleString("pt-BR"):"")+'</small></div><span class="badge">'+esc(o.status||"novo")+'</span></div><div class="meta"><div><small>Cliente</small>'+esc(b.name||"—")+'</div><div><small>WhatsApp</small>'+esc(b.phone||"—")+'</div><div><small>CEP de entrega</small>'+esc(b.cep||"—")+'</div></div><p><small>Endereço de entrega</small>'+esc(b.address||"—")+'</p>'+its.map(x=>'<div class="item"><span>'+esc((x.quantity||1)+"× "+(x.name||"Produto"))+'</span><b>'+money((x.price||0)*(x.quantity||1))+'</b></div>').join("")+'<div class="totals"><span>Produtos: <b>'+money(o.total_products)+'</b></span><span>Frete: <b>'+money(f.price)+'</b></span><strong>Total: '+money(o.grand_total)+'</strong></div><div class="order-actions"><select data-status="'+esc(o.id)+'"><option value="novo">Novo</option><option value="em_separacao">Em separação</option><option value="enviado">Enviado</option><option value="entregue">Entregue</option><option value="cancelado">Cancelado</option></select><button class="print-btn" data-print="'+esc(o.id)+'">🖨 Imprimir pedido</button><button class="label-btn" data-label="'+esc(o.id)+'">🏷 Imprimir etiqueta de envio</button></div></article>}).join(""):'<div class="panel empty">Nenhum pedido encontrado.</div>'}
async function load(){try{const d=await api();orders=Array.isArray(d)?d:[];render(orders);$("#loginMsg").textContent=""}catch(e){$("#summary").textContent="Não foi possível carregar os pedidos";$("#loginMsg").textContent="Painel aberto, mas não foi possível consultar os pedidos: "+e.message}}
function logout(){pin="";sessionStorage.removeItem("esh-admin-pin");$("#app").hidden=true;$("#login").hidden=false}
$("#enter").onclick=async()=>{pin=$("#pin").value.replace(/\D/g,"");$("#loginMsg").textContent="";if(pin!==ADMIN_PIN){$("#loginMsg").textContent="PIN inválido.";return}sessionStorage.setItem("esh-admin-pin",pin);$("#login").hidden=true;$("#app").hidden=false;await load()};
$("#pin").onkeydown=e=>{if(e.key==="Enter")$("#enter").click()};$("#refresh").onclick=load;$("#logout").onclick=logout;
document.addEventListener("change",async e=>{const id=e.target.dataset.status;if(id)try{await api("POST",{id,status:e.target.value});await load()}catch(x){alert(x.message)}});
document.addEventListener("click",e=>{const p=e.target.dataset.print,l=e.target.dataset.label;if(p){const o=orders.find(x=>x.id===p);if(o)printDoc(o,false)}if(l){const o=orders.find(x=>x.id===l);if(o)printDoc(o,true)}});
if(pin===ADMIN_PIN){$("#login").hidden=true;$("#app").hidden=false;load()}
})();