(()=>{"use strict";
const SUPABASE_URL="https://sybxbyaywznbwipbssso.supabase.co",SUPABASE_KEY="sb_publishable_3iXGUzzTaypiGou7K7UFEw_OW1qKljR",ORIGIN_CEP="84261000",WHATSAPP="5542999999999";
const $=s=>document.querySelector(s), money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fallback="data:image/svg+xml;charset=UTF-8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600"><rect width="600" height="600" rx="50" fill="#111722"/><path d="M330 70 170 330h125l-25 200 170-270H315z" fill="#ff2142"/><path d="M330 70 170 330h125l-25 200 170-270H315z" fill="none" stroke="#ffc400" stroke-width="12"/></svg>');
let products=[],cart=[],state={search:"",category:"",brand:"",sort:"relevance"};
function brand(n){return /microwear/i.test(n)?"Microwear":/wearzone/i.test(n)?"Wearzone":/gswear/i.test(n)?"GSWear":/fone|buds/i.test(n)?"Eletroshopp":"Eletroshopp"}
function init(){products=(Array.isArray(window.ELETRO_PRODUCTS)?window.ELETRO_PRODUCTS:[]).map((p,i)=>({...p,id:String(p.id??i),price:Number(p.price)||0,brand:p.brand||brand(p.name),image:p.image||fallback})).filter(p=>p.name&&p.price>0);try{cart=JSON.parse(localStorage.getItem("eletroshopp-cart")||"[]")}catch(e){cart=[]}bind();renderAll();setTimeout(()=>$("#splash")?.classList.add("hide"),1400)}
function bind(){document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.add)add(b.dataset.add);else if(b.dataset.category!==undefined){state.category=b.dataset.category;renderAll()}else if(b.dataset.brand!==undefined){state.brand=b.dataset.brand;renderAll()}else if(b.dataset.openCart!==undefined)open("#cart");else if(b.dataset.closeCart!==undefined)close("#cart");else if(b.dataset.checkout!==undefined)checkout();else if(b.dataset.closeCheckout!==undefined)close("#checkout");else if(b.dataset.minus)qty(b.dataset.minus,-1);else if(b.dataset.plus)qty(b.dataset.plus,1);else if(b.dataset.remove){cart=cart.filter(x=>x.id!==b.dataset.remove);save()}else if(b.dataset.freight)freight();else if(b.dataset.finish)finish();else if(b.dataset.scrollCatalog)$("#catalogo")?.scrollIntoView({behavior:"smooth"})});
$("#search")?.addEventListener("input",e=>{state.search=e.target.value;renderProducts()});$("#sort")?.addEventListener("change",e=>{state.sort=e.target.value;renderProducts()})}
function save(){localStorage.setItem("eletroshopp-cart",JSON.stringify(cart));renderCart()}
function count(){return cart.reduce((a,x)=>a+(+x.qty||1),0)}function total(){return cart.reduce((a,x)=>a+(+x.price||0)*(+x.qty||1),0)}
function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
function add(id){const p=products.find(x=>x.id===String(id));if(!p)return toast("Produto não encontrado");const x=cart.find(x=>x.id===p.id);x?x.qty=(+x.qty||1)+1:cart.push({id:p.id,name:p.name,price:p.price,image:p.image,qty:1});save();open("#cart");toast("Produto adicionado ao carrinho")}
function qty(id,d){const x=cart.find(x=>x.id===String(id));if(!x)return;x.qty=(+x.qty||1)+d;if(x.qty<=0)cart=cart.filter(y=>y!==x);save()}
function open(id){$(id)?.classList.add("open");document.body.classList.add("locked")}function close(id){$(id)?.classList.remove("open");if(!document.querySelector(".drawer.open"))document.body.classList.remove("locked")}
function filtered(){const q=state.search.trim().toLowerCase();let a=products.filter(p=>(!state.category||p.category===state.category)&&(!state.brand||p.brand===state.brand)&&(!q||[p.name,p.description,p.category,p.brand].join(" ").toLowerCase().includes(q)));if(state.sort==="priceAsc")a.sort((x,y)=>x.price-y.price);if(state.sort==="priceDesc")a.sort((x,y)=>y.price-x.price);if(state.sort==="name")a.sort((x,y)=>x.name.localeCompare(y.name));return a}
function card(p){return '<article class="product-card"><div class="product-img"><img src="'+esc(p.image||fallback)+'" alt="'+esc(p.name)+'" onerror="this.onerror=null;this.src=\''+fallback+'\'"></div><div class="product-info"><span class="eyebrow">'+esc(p.category)+'</span><h3>'+esc(p.name)+'</h3><p>'+esc(p.description)+'</p><div class="price">'+money(p.price)+'</div><button class="add" data-add="'+esc(p.id)+'">Adicionar ao carrinho</button></div></article>'}
function renderFilters(){const cats=[...new Set(products.map(p=>p.category))].sort(),brands=[...new Set(products.map(p=>p.brand))].sort();$("#cats").innerHTML='<button class="chip '+(!state.category?"active":"")+'" data-category="">Todos</button>'+cats.map(x=>'<button class="chip '+(state.category===x?"active":"")+'" data-category="'+esc(x)+'">'+esc(x)+'</button>').join("");$("#brands").innerHTML='<button class="chip '+(!state.brand?"active":"")+'" data-brand="">Todas</button>'+brands.map(x=>'<button class="chip '+(state.brand===x?"active":"")+'" data-brand="'+esc(x)+'">'+esc(x)+'</button>').join("")}
function renderProducts(){const a=filtered();$("#products").innerHTML=a.length?a.map(card).join(""):'<div class="empty">Nenhum produto encontrado.</div>';$("#count").textContent=a.length+" produtos disponíveis"}
function renderFeatured(){const a=products.slice(0,10);$("#featured").innerHTML=a.map(card).join("")}
function renderCart(){if(!cart.length)$("#cartItems").innerHTML='<div class="empty">Seu carrinho está vazio.</div>';else $("#cartItems").innerHTML=cart.map(x=>'<div class="cart-row"><img src="'+esc(x.image||fallback)+'" alt=""><div><b>'+esc(x.name)+'</b><small>'+money(x.price)+'</small><div class="qty"><button data-minus="'+esc(x.id)+'">−</button><span>'+x.qty+'</span><button data-plus="'+esc(x.id)+'">+</button><button class="remove" data-remove="'+esc(x.id)+'">Excluir</button></div></div></div>').join("");$("#cartTotal").textContent=money(total());$("#cartCount").textContent=count()}
function renderAll(){if(!products.length){$("#products").innerHTML='<div class="empty">Catálogo temporariamente indisponível.</div>';return}renderFilters();renderFeatured();renderProducts();renderCart()}
function checkout(){if(!cart.length)return toast("Adicione produtos primeiro");$("#orderSummary").innerHTML=cart.map(x=>'<div>'+x.qty+'× '+esc(x.name)+' <b>'+money(x.price*x.qty)+'</b></div>').join("");$("#orderSubtotal").textContent=money(total());close("#cart");open("#checkout")}
async function freight(){const cep=($("#cep").value||"").replace(/\D/g,"");if(cep.length!==8)return toast("Digite um CEP válido");$("#freight").innerHTML='<div class="empty">Calculando frete…</div>';try{const r=await fetch(SUPABASE_URL+"/functions/v1/frenet-quote",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+SUPABASE_KEY},body:JSON.stringify({fromPostalCode:ORIGIN_CEP,toPostalCode:cep,items:cart.map(x=>({sku:x.id,quantity:x.qty,price:x.price,weight:1,width:15,height:10,length:20}))})});const d=await r.json();if(!r.ok||!Array.isArray(d.quotes)||!d.quotes.length)throw Error(d.error||"Frete indisponível");$("#freight").innerHTML=d.quotes.slice(0,5).map((q,i)=>'<label class="freight-option"><input type="radio" name="shipping" value="'+esc(JSON.stringify(q))+'" '+(i===0?"checked":"")+'><span><b>'+esc(q.name||q.company||"Entrega")+'</b><small>'+esc(q.days||"")+" dias</small></span><strong>"+money(q.price)+"</strong></label>").join("")}catch(e){$("#freight").innerHTML='<div class="freight-error">'+esc(e.message)+'</div>'}}
async function finish(){const name=$("#buyerName").value.trim(),phone=$("#buyerPhone").value.trim(),cep=($("#cep").value||"").replace(/\D/g,""),address=$("#buyerAddress").value.trim(),si=document.querySelector('input[name="shipping"]:checked');if(!name||!phone||cep.length!==8||!address||!si)return toast("Preencha os dados e calcule o frete");const shipping=JSON.parse(si.value),order={id:"ESH-"+Date.now(),customer:{name,phone,cep,address},items:cart.map(x=>({id:x.id,name:x.name,price:x.price,quantity:x.qty})),subtotal:total(),freight:shipping,total:total()+Number(shipping.price||0),created_at:new Date().toISOString()};const btn=document.querySelector('[data-finish]');btn.disabled=true;btn.textContent="Registrando pedido…";try{const r=await fetch(SUPABASE_URL+"/functions/v1/create-order",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+SUPABASE_KEY},body:JSON.stringify(order)}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Não foi possível registrar o pedido");const msg=["Olá! Quero fazer este pedido na Eletroshopp.","Pedido: "+order.id,"Cliente: "+name,"Total: "+money(order.total),"",...order.items.map(x=>x.quantity+"x "+x.name+" - "+money(x.price*x.quantity))].join("\n");cart=[];save();location.href="https://wa.me/"+WHATSAPP+"?text="+encodeURIComponent(msg)}catch(e){toast(e.message);btn.disabled=false;btn.textContent="Finalizar pedido pelo WhatsApp"}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
})();