(() => {
"use strict";
const SUPABASE_URL="https://sybxbyaywznbwipbssso.supabase.co";
const SUPABASE_KEY="sb_publishable_3iXGUzzTaypiGou7K7UFEw_OW1qKljR";
const ORIGIN_CEP="84261000";
const WHATSAPP="5542999999999";
const $=s=>document.querySelector(s);
const money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fallback="data:image/svg+xml;charset=UTF-8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600"><rect width="600" height="600" rx="50" fill="#111522"/><circle cx="300" cy="300" r="170" fill="#171d2a"/><path d="M335 90 205 310h100l-25 200 140-250H315z" fill="#ff2442"/><path d="M335 90 315 260h105l-140 250 25-200H205z" fill="#ffc400"/></svg>');
const products=(Array.isArray(window.ELETRO_PRODUCTS)?window.ELETRO_PRODUCTS:[]).map((p,i)=>({id:String(p.id??i),name:p.name||"Produto",description:p.description||"Produto Eletroshopp.",price:Number(p.price)||0,category:p.category||"Outros",brand:p.brand||p.marca||p.category||"Eletroshopp",image:p.image||fallback}));
let cart=[];try{cart=JSON.parse(localStorage.getItem("eletroshopp-cart")||"[]")}catch(e){cart=[]}
let state={search:"",category:"",brand:"",sort:"relevance"};
function toast(m){let t=$("#toast");if(!t){t=document.createElement("div");t.id="toast";t.className="toast";document.body.appendChild(t)}t.textContent=m;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),1800)}
function count(){return cart.reduce((n,x)=>n+(Number(x.qty)||1),0)}
function total(){return cart.reduce((n,x)=>n+(Number(x.price)||0)*(Number(x.qty)||1),0)}
function save(){localStorage.setItem("eletroshopp-cart",JSON.stringify(cart));renderCart();$("#cartCount").textContent=count()}
function add(id){const p=products.find(x=>x.id===String(id));if(!p)return toast("Produto não encontrado");const x=cart.find(x=>x.id===p.id);if(x)x.qty=(Number(x.qty)||1)+1;else cart.push({id:p.id,name:p.name,price:p.price,image:p.image,qty:1});save();open("#cart");toast("Produto adicionado ao carrinho")}
function qty(id,d){const x=cart.find(x=>x.id===String(id));if(!x)return;x.qty=(Number(x.qty)||1)+d;if(x.qty<=0)cart=cart.filter(y=>y!==x);save()}
function open(id){$(id)?.classList.add("open");document.body.classList.add("locked")}
function close(id){$(id)?.classList.remove("open");if(!document.querySelector(".drawer.open"))document.body.classList.remove("locked")}
function card(p){return '<article class="product-card"><div class="product-img"><img loading="lazy" src="'+p.image+'" alt="'+esc(p.name)+'" onerror="this.onerror=null;this.src=''+fallback+''"></div><div class="product-info"><span class="eyebrow">'+esc(p.category)+'</span><h3>'+esc(p.name)+'</h3><p>'+esc(p.description)+'</p><strong>'+money(p.price)+'</strong><button type="button" class="add" data-add="'+esc(p.id)+'">🛒 Adicionar ao carrinho</button></div></article>'}
function filtered(){let q=state.search.toLowerCase().trim();let r=products.filter(p=>(!state.category||p.category===state.category)&&(!state.brand||p.brand===state.brand)&&(!q||[p.name,p.description,p.category,p.brand].join(" ").toLowerCase().includes(q)));if(state.sort==="priceAsc")r.sort((a,b)=>a.price-b.price);if(state.sort==="priceDesc")r.sort((a,b)=>b.price-a.price);return r}
function filters(){let cats=[...new Set(products.map(p=>p.category).filter(Boolean))].sort();let brands=[...new Set(products.map(p=>p.brand).filter(Boolean))].sort();$("#cats").innerHTML='<button class="chip '+(!state.category?"active":"")+'" data-category="">Todos</button>'+cats.map(x=>'<button class="chip '+(state.category===x?"active":"")+'" data-category="'+esc(x)+'">'+esc(x)+'</button>').join("");$("#brands").innerHTML='<button class="chip '+(!state.brand?"active":"")+'" data-brand="">Todas</button>'+brands.map(x=>'<button class="chip '+(state.brand===x?"active":"")+'" data-brand="'+esc(x)+'">'+esc(x)+'</button>').join("")}
function render(){let r=filtered();$("#products").innerHTML=r.length?r.map(card).join(""):'<div class="empty">Nenhum produto encontrado.</div>';$("#count").textContent=r.length+" produtos encontrados";$("#featured").innerHTML=products.slice(0,8).map(card).join("");filters();$("#cartCount").textContent=count();renderCart()}
function renderCart(){let c=$("#cartItems");if(!cart.length)c.innerHTML='<div class="empty">Seu carrinho está vazio.<br>Adicione um produto para continuar.</div>';else c.innerHTML=cart.map(x=>'<div class="cart-row"><img src="'+(x.image||fallback)+'" onerror="this.src=\''+fallback+'\'"><div><b>'+esc(x.name)+'</b><small>'+money(x.price)+'</small><div class="qty"><button type="button" data-minus="'+esc(x.id)+'">−</button><span>'+x.qty+'</span><button type="button" data-plus="'+esc(x.id)+'">+</button><button type="button" class="remove" data-remove="'+esc(x.id)+'">Excluir</button></div></div></div>').join("");$("#cartTotal").textContent=money(total())}
function checkout(){if(!cart.length)return toast("Adicione produtos primeiro");$("#orderSummary").innerHTML=cart.map(x=>"<div>"+x.qty+"× "+esc(x.name)+" <b>"+money(x.price*x.qty)+"</b></div>").join("");$("#orderSubtotal").textContent=money(total());close("#cart");open("#checkout")}
async function freight(){let cep=($("#cep").value||"").replace(/\D/g,"");if(cep.length!==8)return toast("Digite um CEP válido");$("#freight").innerHTML='<span class="loading">Calculando frete…</span>';try{let r=await fetch(SUPABASE_URL+"/functions/v1/frenet-quote",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+SUPABASE_KEY},body:JSON.stringify({fromPostalCode:ORIGIN_CEP,toPostalCode:cep,items:cart.map(x=>({sku:x.id,quantity:x.qty,price:x.price,weight:1,width:15,height:10,length:20}))})});let d=await r.json();if(!r.ok||!Array.isArray(d.quotes)||!d.quotes.length)throw Error(d.error||"Frete indisponível");$("#freight").innerHTML=d.quotes.slice(0,4).map((q,i)=>'<label class="freight-option"><input type="radio" name="shipping" value=''+esc(JSON.stringify(q))+'' '+(i===0?"checked":"")+'><span><b>'+esc(q.name||q.company||"Entrega")+'</b><small>'+esc(q.days||"")+" dias</small></span><strong>"+money(q.price)+"</strong></label>").join("")}catch(e){$("#freight").innerHTML='<div class="freight-error">'+esc(e.message)+"</div>"}}
async function finish(){let name=$("#buyerName").value.trim(),phone=$("#buyerPhone").value.trim(),cep=($("#cep").value||"").replace(/\D/g,""),address=$("#buyerAddress").value.trim(),si=document.querySelector('input[name="shipping"]:checked');if(!name||!phone||cep.length!==8||!address||!si)return toast("Preencha os dados e calcule o frete");let shipping=JSON.parse(si.value),order={id:"ESH-"+Date.now(),customer:{name,phone,cep,address},items:cart.map(x=>({id:x.id,name:x.name,price:x.price,quantity:x.qty})),subtotal:total(),freight:shipping,total:total()+Number(shipping.price||0),created_at:new Date().toISOString()};let b=$("#finish");b.disabled=true;b.textContent="Enviando pedido…";try{let r=await fetch(SUPABASE_URL+"/functions/v1/create-order",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+SUPABASE_KEY},body:JSON.stringify(order)}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Não foi possível registrar o pedido");let msg=["Olá! Quero fazer este pedido na Eletroshopp.","Pedido: "+order.id,"Cliente: "+name,"Total: "+money(order.total),"",...order.items.map(x=>x.quantity+"x "+x.name+" - "+money(x.price*x.quantity))].join("\n");cart=[];save();location.href="https://wa.me/"+WHATSAPP+"?text="+encodeURIComponent(msg)}catch(e){toast(e.message);b.disabled=false;b.textContent="Finalizar pedido"}}
document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.add!==undefined)add(b.dataset.add);else if(b.dataset.category!==undefined){state.category=b.dataset.category;render()}else if(b.dataset.brand!==undefined){state.brand=b.dataset.brand;render()}else if(b.dataset.minus!==undefined)qty(b.dataset.minus,-1);else if(b.dataset.plus!==undefined)qty(b.dataset.plus,1);else if(b.dataset.remove!==undefined){cart=cart.filter(x=>x.id!==b.dataset.remove);save()}else if(b.dataset.openCart!==undefined)open("#cart");else if(b.dataset.closeCart!==undefined)close("#cart");else if(b.dataset.checkout!==undefined)checkout();else if(b.dataset.closeCheckout!==undefined)close("#checkout");else if(b.dataset.freight!==undefined)freight();else if(b.dataset.finish!==undefined)finish()},true);
$("#search")?.addEventListener("input",e=>{state.search=e.target.value;render()});
$("#sort")?.addEventListener("change",e=>{state.sort=e.target.value;render()});
if(products.length){render()}else{$("#products").innerHTML='<div class="empty">Catálogo temporariamente indisponível.</div>'}
window.Eletroshopp={addToCart:add,cart};
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js?v=20261004-rebuild2").catch(()=>{}));
})();