import { products } from './data/products.js';
import { calculateFreight } from './services/freight.js';
import { createOrder } from './services/orders.js';

const $=s=>document.querySelector(s);
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
const state={items:JSON.parse(localStorage.getItem('eletroshopp-cart')||'[]'),freight:null,payment:''};
const save=()=>localStorage.setItem('eletroshopp-cart',JSON.stringify(state.items));
const total=()=>state.items.reduce((s,p)=>s+p.price*p.qty,0);
function renderCategories(){const c=[...new Set(products.map(p=>p.category))].sort((a,b)=>a.localeCompare(b,'pt-BR'));$('#category').innerHTML='<option value="">Todas as categorias</option>'+c.map(x=>'<option>'+x+'</option>').join('')}
function filtered(){const q=$('#search').value.trim().toLowerCase(),c=$('#category').value;return products.filter(p=>(!q||p.name.toLowerCase().includes(q)||p.description.toLowerCase().includes(q))&&(!c||p.category===c))}
function render(){const list=filtered();$('#status').textContent=list.length+' produtos no catálogo';$('#products').innerHTML=list.map(p=>'<article class="card '+(p.available?'':'soldout')+'"><img src="'+p.image+'" alt="'+p.name+'" loading="lazy"><div class="card-body"><span class="category">'+p.category+'</span><h3>'+p.name+'</h3>'+(p.available?'<strong class="price">'+money(p.price)+'</strong><button data-add="'+p.id+'" type="button">Adicionar ao carrinho</button>':'<span class="sold-label">Esgotado</span>')+'</div></article>').join('')}
function renderCart(){const count=state.items.reduce((s,p)=>s+p.qty,0);$('#cartCount').textContent=count;$('#cartTotal').textContent=money(total());$('#cartItems').innerHTML=state.items.length?state.items.map(i=>'<div class="cart-row"><div><b>'+i.name+'</b><small>'+money(i.price)+' cada</small></div><div class="qty"><button data-dec="'+i.id+'">−</button><b>'+i.qty+'</b><button data-inc="'+i.id+'">+</button><button class="remove" data-remove="'+i.id+'">×</button></div></div>').join(''):'<p class="empty">Seu carrinho está vazio.</p>'}
function summary(){const f=state.freight?.price||0;$('#orderSummary').innerHTML='<div><span>Produtos</span><b>'+money(total())+'</b></div><div><span>Frete</span><b>'+(state.freight?money(f):'A calcular')+'</b></div><div class="grand"><span>Total</span><b>'+money(total()+f)+'</b></div>'}
function openCart(){$('#cartPanel').classList.add('open');$('#backdrop').classList.add('show')}
function closeCart(){$('#cartPanel').classList.remove('open');$('#backdrop').classList.remove('show')}
function openCheckout(){if(!state.items.length)return alert('Seu carrinho está vazio.');closeCart();state.freight=null;state.payment='';document.querySelectorAll('.payments button').forEach(b=>b.classList.remove('selected'));$('#freightResults').innerHTML='';summary();$('#checkoutModal').classList.remove('hidden')}
function closeCheckout(){$('#checkoutModal').classList.add('hidden')}
document.addEventListener('click',e=>{const a=e.target.dataset.add,i=e.target.dataset.inc,d=e.target.dataset.dec,r=e.target.dataset.remove;if(a){const p=products.find(x=>x.id===a),old=state.items.find(x=>x.id===a);old?old.qty++:state.items.push({id:p.id,name:p.name,price:p.price,image:p.image,qty:1});save();renderCart();return}if(i||d||r){const id=i||d||r,x=state.items.find(y=>y.id===id);if(!x)return;if(i)x.qty++;if(d)x.qty--;if(r)x.qty=0;state.items=state.items.filter(y=>y.qty>0);save();renderCart();return}if(e.target.closest('#cartButton'))openCart();if(e.target.closest('#closeCart'))closeCart();if(e.target.id==='backdrop')closeCart();if(e.target.closest('#checkout'))openCheckout();if(e.target.closest('#closeCheckout'))closeCheckout();const pay=e.target.closest('.payments button');if(pay){state.payment=pay.dataset.payment;document.querySelectorAll('.payments button').forEach(b=>b.classList.remove('selected'));pay.classList.add('selected')}});
$('#search').addEventListener('input',render);$('#category').addEventListener('change',render);
$('#buyerCep').addEventListener('input',e=>{let v=e.target.value.replace(/\D/g,'').slice(0,8);e.target.value=v.length>5?v.slice(0,5)+'-'+v.slice(5):v});
$('#buyerCep').addEventListener('blur',async()=>{const cep=$('#buyerCep').value.replace(/\D/g,'');if(cep.length!==8)return;try{const d=await (await fetch('https://viacep.com.br/ws/'+cep+'/json/')).json();if(!d.erro){$('#buyerAddress').value=d.logradouro||'';$('#buyerNeighborhood').value=d.bairro||'';$('#buyerCity').value=[d.localidade,d.uf].filter(Boolean).join('/')}}catch(e){console.warn(e)}});
$('#freightBtn').addEventListener('click',async()=>{const cep=$('#buyerCep').value.replace(/\D/g,'');if(cep.length!==8)return alert('Informe um CEP válido.');$('#freightResults').innerHTML='<div class="loading">⏳ Consultando tarifas reais...</div>';try{const q=await calculateFreight(cep,state.items);state.freight={...q,price:Number(q.options[0].price),id:String(q.options[0].id),days:q.options[0].days};$('#freightResults').innerHTML=q.options.map((o,i)=>'<button class="freight-option '+(i===0?'selected':'')+'" data-freight="'+i+'" type="button">🚚 <b>'+((o.company?o.company+' — ':'')+(o.name||'Frete'))+'</b><small>'+String(o.days??'consulte')+' dias úteis • '+money(o.price)+'</small></button>').join('');summary()}catch(e){console.error(e);$('#freightResults').innerHTML='<div class="error">'+(e.message||'Não foi possível calcular o frete.')+'</div>'}});
$('#freightResults').addEventListener('click',e=>{const b=e.target.closest('[data-freight]');if(!b||!state.freight)return;const o=state.freight.options[Number(b.dataset.freight)];state.freight={...state.freight,price:Number(o.price),id:String(o.id),days:o.days};document.querySelectorAll('.freight-option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');summary()});
$('#confirmOrder').addEventListener('click',async()=>{if(!state.freight)return alert('Calcule o frete primeiro.');if(!state.payment)return alert('Selecione a forma de pagamento.');const buyer={name:$('#buyerName').value.trim(),phone:$('#buyerPhone').value.trim(),cep:$('#buyerCep').value.trim(),address:$('#buyerAddress').value.trim(),number:$('#buyerNumber').value.trim(),neighborhood:$('#buyerNeighborhood').value.trim(),city:$('#buyerCity').value.trim(),complement:$('#buyerComplement').value.trim(),note:$('#buyerNote').value.trim()};if(!buyer.name||!buyer.phone||!buyer.cep||!buyer.address||!buyer.number||!buyer.neighborhood||!buyer.city)return alert('Preencha os dados obrigatórios.');const b=$('#confirmOrder');b.disabled=true;b.textContent='Registrando pedido...';try{const order=await createOrder({items:state.items,freight:state.freight,buyer,payment:state.payment,totalProducts:total()});const lines=order.items.map(i=>'• '+i.qty+'x '+i.name+' — '+money(i.price*i.qty)).join('\n');const msg='Olá! Quero confirmar o pedido *'+order.id+'* da Eletroshopp.\n\n'+lines+'\n\nProdutos: '+money(order.totalProducts)+'\nFrete: '+money(order.freight.price)+' ('+(order.freight.days||'prazo a confirmar')+')\nTotal: '+money(order.grandTotal)+'\nPagamento: '+order.payment+'\n\nCliente: '+buyer.name+'\nWhatsApp: '+buyer.phone+'\nEndereço: '+buyer.address+', '+buyer.number+' — '+buyer.neighborhood+' — '+buyer.city+' — CEP '+buyer.cep+(buyer.complement?'\nComplemento: '+buyer.complement:'')+(buyer.note?'\nObservação: '+buyer.note:'');state.items=[];save();location.href='https://wa.me/5542998157736?text='+encodeURIComponent(msg)}catch(e){console.error(e);alert('Não foi possível registrar o pedido.\n\n'+(e.message||e))}finally{b.disabled=false;b.textContent='Confirmar pedido e abrir WhatsApp'}});
renderCategories();render();renderCart();summary();